### ISSUE TITLE
"Cannot find module" on version 6.0.0

### ISSUE THREAD

**Issue by 2colours** [casperiv0/pastebin-api#169]
Hi Casper,

when I upgraded to version 6.0.0, I got the following error at my import statement:
```ts
import { PasteClient } from 'pastebin-api';
```

***cannot find module 'pastebin-api' or its corresponding type declarations***

Indeed, there seems to be something wrong about this release: under the `node_modules` folder of this module, there used to be a `dist` folder. Now there is nothing instead.

Could you please look into this problem?

I don't think this is environment specific but for good manners: running Node v18.7.0 with Yarn 1.22.19, on a WSL Ubuntu 20.04 (`5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by casperiv0** [comment]
Thank you for the detailed issue report! Indeed, somehow it didn't upload the compiled code. This should now be fixed on `6.1.0`. Are you able to update and verify this is fixed, thanks!

**Comment by 2colours** [comment]
Oh nice, it seems to be okay with the update. :) That was quick. Thank you, still going pastebin-api still going strong! 💪
